### PR TITLE
Solve problem 42 with a sliding window

### PR DESCRIPTION
**Pull request by nmyers217**
This took me way too long.

### CODE REVIEW

**Comment by GeorgeNav** [comment]
image

```ts
function trap(heights: number[]): number {
  let total = 0;
  heights.forEach((height, i) => {
    let [leftMaxIdx, rightMaxIdx] = [i, i];
    let [leftMax, rightMax] = [height, height];
    // find closest tallest wall to the left
    while (--leftMaxIdx >= 0) {
      if (heights[leftMaxIdx] > leftMax)
        leftMax = heights[leftMaxIdx];
    };
    if (leftMax === height)
      return;

    // find closest tallest wall to the right
    while (++rightMaxIdx < heights.length) {
      if (heights[rightMaxIdx] > rightMax)
        rightMax = heights[rightMaxIdx];
    };
    if (rightMax === height)
      return;

    // add to total
    total += Math.min(leftMax, rightMax) - height;
  });
  return total;
}
```

**Review by GeorgeNav — APPROVED** [review]

**Comment by nmyers217** [comment]
Looks good.
Idk why, but `Array.forEach` makes me cringe these days and I always try to use a native for loop with `for (const el of arr)` or `for (const [i, el] of arr.entries())`.
I think async await has trained me to avoid `forEach`.

Which solution do you want to merge?

**Comment by GeorgeNav** [comment]
I'd say yours is probably better to merge because the run time is better. I just want to try the solution myself.

**Comment by GeorgeNav** [comment]
it's funny because async await taught me the opposite when using Promise.all. If parallelism isn't needed the native for loop I agree is useful

**Comment by nmyers217** [comment]
Oh yeah, doing something like `await Promise.allSettled(arr.map(Promise.resolve))` is really useful because `Array.map` is actually functional. I still don't know a good use case for `Array.forEach` though.

**Pull request merged**
